//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.12 at 09:58:13 AM EST 
//


package edu.stevens.cs.cs548.rest.representation;

import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (edu.stevens.cs.cs548.clinic.service.dto.DateAdapter.parseDate(value));
    }

    public String marshal(Date value) {
        return (edu.stevens.cs.cs548.clinic.service.dto.DateAdapter.printDate(value));
    }

}
