//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.12 at 09:58:13 AM EST 
//


package edu.stevens.cs.cs548.rest.representation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.stevens.cs.cs548.rest.representation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Patient_QNAME = new QName("http://www.example.org/clinic/TreatmentDTO", "patient");
    private final static QName _Treatment_QNAME = new QName("http://www.example.org/clinic/TreatmentDTO", "treatment");
    private final static QName _Provider_QNAME = new QName("http://www.example.org/clinic/TreatmentDTO", "provider");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.stevens.cs.cs548.rest.representation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TreatmentType }
     * 
     */
    public TreatmentType createTreatmentType() {
        return new TreatmentRepresentation();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderRepresentation();
    }

    /**
     * Create an instance of {@link PatientType.Treatments }
     * 
     */
    public PatientType.Treatments createPatientTypeTreatments() {
        return new PatientType.Treatments();
    }

    /**
     * Create an instance of {@link RadiologyType }
     * 
     */
    public RadiologyType createRadiologyType() {
        return new RadiologyType();
    }

    /**
     * Create an instance of {@link SurgeryType }
     * 
     */
    public SurgeryType createSurgeryType() {
        return new SurgeryType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientRepresentation();
    }

    /**
     * Create an instance of {@link ProviderType.Treatments }
     * 
     */
    public ProviderType.Treatments createProviderTypeTreatments() {
        return new ProviderType.Treatments();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link DrugTreatmentType }
     * 
     */
    public DrugTreatmentType createDrugTreatmentType() {
        return new DrugTreatmentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientType }{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
	@XmlElementDecl(namespace = "http://www.example.org/clinic/TreatmentDTO", name = "patient")
    public JAXBElement<PatientType> createPatient(PatientType value) {
        return new JAXBElement<PatientType>(_Patient_QNAME, ((Class) PatientRepresentation.class), null, ((PatientRepresentation) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TreatmentType }{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    @XmlElementDecl(namespace = "http://www.example.org/clinic/TreatmentDTO", name = "treatment")
    public JAXBElement<TreatmentType> createTreatment(TreatmentType value) {
        return new JAXBElement<TreatmentType>(_Treatment_QNAME, ((Class) TreatmentRepresentation.class), null, ((TreatmentRepresentation) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProviderType }{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    @XmlElementDecl(namespace = "http://www.example.org/clinic/TreatmentDTO", name = "provider")
    public JAXBElement<ProviderType> createProvider(ProviderType value) {
        return new JAXBElement<ProviderType>(_Provider_QNAME, ((Class) ProviderRepresentation.class), null, ((ProviderRepresentation) value));
    }

}
