ALTER TABLE TREATMENT DROP CONSTRAINT TREATMENTPATIENTID
ALTER TABLE PATIENT DROP CONSTRAINT PATIENT_CLINIC_ID
ALTER TABLE CLINIC_PATIENT DROP CONSTRAINT CLNCPATIENTClnicID
ALTER TABLE CLINIC_PATIENT DROP CONSTRAINT CLNCPATIENTptntsID
ALTER TABLE PATIENT_TREATMENT DROP CONSTRAINT PTNTTREATMENTPtntD
ALTER TABLE PATIENT_TREATMENT DROP CONSTRAINT PTNTTRTMNTtrtmntsD
DROP TABLE CLINIC
DROP TABLE TREATMENT
DROP TABLE PATIENT
DROP TABLE PROVIDER
DROP TABLE CLINIC_PATIENT
DROP TABLE PATIENT_TREATMENT
